# ------------------------------
# Module "PSNetworkAdministrator"
# Generated by: Niklas Schneider
# Generated on: 02.02.2026
# ------------------------------

# ===== Dot-source all private, public and service functions =====
try {
    Get-ChildItem -Path "$PSScriptRoot\Private\*.ps1" | ForEach-Object {
        . $_.FullName
    }
    Get-ChildItem -Path "$PSScriptRoot\Public\*.ps1" -ErrorAction Stop | ForEach-Object {
        . $_.FullName
    }
    Get-ChildItem -Path "$PSScriptRoot\Services\*.ps1" -ErrorAction Stop | ForEach-Object {
        . $_.FullName
    }
}
catch {
    $RefValue = '<PSNetworkAdministrator|Module>'
    $MessageText = 'Failed to dot-source all functions'
    $ErrorMessage = "$MessageText | Ref=$RefValue | Exception=$($_.Exception.Message)"

    Write-Warning $ErrorMessage
    throw $ErrorMessage
}

# ===== Load config and initialize path for logs =====
try {
    $script:ModuleConfig = Initialize-Configuration
    $script:LoggingPath = $script:ModuleConfig.Logging.LoggingPath
}
catch {
    $RefValue = '<PSNetworkAdministrator|Module|Config>'
    $ExceptionMessage = "$($_.Exception.Message)"
    $ErrorMessage = if ($ExceptionMessage.StartsWith('[')) {
        "[IOx0000002] Failed to load file | Ref=$RefValue >> $ExceptionMessage"
    }
    else {
        "[IOx0000002] Failed to load file | Ref=$RefValue | Exception=$ExceptionMessage"
    }

    Write-Warning $ErrorMessage
    throw $ErrorMessage
}

# ===== Check module availability: ActiveDirectory, CredentialManager =====
if (-not (Get-Module -ListAvailable -Name CredentialManager) -or -not (Get-Module -ListAvailable -Name ActiveDirectory)) {
    $ErrorMessages = @()
    if (-not (Get-Module -ListAvailable -Name ActiveDirectory)) {
        $Message = Get-ErrorMessages -ErrorCode 'SYx0000009' -RefValue '<ActiveDirectory>' -Language $script:ModuleConfig.Language
        $ErrorMessages += $Message
    }
    if (-not (Get-Module -ListAvailable -Name CredentialManager)) {
        $Message = Get-ErrorMessages -ErrorCode 'SYx0000009' -RefValue '<CredentialManager>' -Language $script:ModuleConfig.Language
        $ErrorMessages += $Message
    }
    $ErrorMessage = $ErrorMessages -join '; '

    Write-AppLogging -LoggingMessage $ErrorMessage -LoggingLevel 'Error' -Language $script:ModuleConfig.Language
    throw $ErrorMessage
}

# ===== Import modules: CredentialManager, ActiveDirectory =====
try {
    Import-Module CredentialManager -ErrorAction Stop
    Import-Module ActiveDirectory -ErrorAction Stop
}
catch {
    $RefValue = '<ActiveDirectory|CredentialManager>'
    $ErrorMessage = Get-ErrorMessages -ErrorCode 'SYx0000010' -ExceptionMessage "$($_.Exception.Message)" -RefValue $RefValue -Language $script:ModuleConfig.Language
    
    Write-AppLogging -LoggingMessage $ErrorMessage -LoggingLevel 'Warning' -Language $script:ModuleConfig.Language
}

# ===== SQLite dependency =====

# Check if folders exist and create them
foreach ($DBPath in @($script:ModuleConfig.Database.DBFolder, $script:ModuleConfig.Database.DepsFolder)) {
    if (-not (Test-Path -LiteralPath $DBPath)) {New-Item -ItemType Directory -Path $DBPath -Force | Out-Null}
}

# Default DB file path
$script:DBFilePath = Join-Path $script:ModuleConfig.Database.DBFolder "$($script:ModuleConfig.Database.DBName)"

# Load SQLite provider DLL
$script:SQLiteAvailable = $false
$SQLiteDll = Join-Path $script:ModuleConfig.Database.DepsFolder 'Microsoft.Data.Sqlite.dll'

if (Test-Path -LiteralPath $SQLiteDll) {
    try {
        Add-Type -Path $SQLiteDll -ErrorAction Stop
        $script:SQLiteAvailable = $true
    }
    catch {
        $script:SQLiteAvailable = $false
        
        $RefValue = '<PSNetworkAdministrator|Module>'
        $ErrorMessage = Get-ErrorMessages -ErrorCode 'SYx0000005' -ExceptionMessage "$($_.Exception.Message)" -RefValue $RefValue -Language $script:ModuleConfig.Language
    
        Write-AppLogging -LoggingMessage $ErrorMessage -LoggingLevel 'Warning' -Language $script:ModuleConfig.Language
    }
}
else {
    $RefValue = '<PSNetworkAdministrator|Module>'
    $ErrorMessage = Get-ErrorMessages -ErrorCode 'SYx0000006' -RefValue $RefValue -Language $script:ModuleConfig.Language
    
    Write-AppLogging -LoggingMessage $ErrorMessage -LoggingLevel 'Warning' -Language $script:ModuleConfig.Language
}