# ------------------------------
# manifest for the module "PSNetworkAdministrator"
# generated by: Niklas Schneider
# generated on: 02.02.2026
# ------------------------------

@{
    # module for this manifest
    RootModule = 'PSNetworkAdministrator.psm1'

    # version number of the module
    ModuleVersion = '1.0'

    # supported PSEditions
    # CompatiblePSEditions = @()

    # ID of the module
    # GUID = ''

    # Author of the module
    Author = 'Niklas Schneider'

    # Copyright
    Copyright = '2026 Niklas Schneider'

    # Description of the module functions
    Description = 'PowerShell Network Administration Tool'

    # functions to export from this module
    FunctionsToExport = @(
    'Test-ExecutionContext',
    'Test-OperatingSystem', 
    'Test-PowerShellVersion'
    )
}