# ------------------------------
# manifest for the module "PSNetworkAdministrator"
# generated by: Niklas Schneider
# generated on: 02.02.2026
# ------------------------------

@{
    # module for this manifest
    RootModule = 'PSNetworkAdministrator.psm1'

    # version number of the module
    ModuleVersion = '1.0.0'

    # ID of the module
    # GUID = ''

    # supported PSEditions
    PowerShellVersion = '7.0'
    CompatiblePSEditions = @('Core', 'Desktop')

    # required PSModules
    RequiredModules = @(
        @{ ModuleName = 'CredentialManager'; ModuleVersion = '2.0' },
        @{ ModuleName = 'ActiveDirectory'; ModuleVersion = '1.0' }
    )

    # Author of the module
    Author = 'Niklas Schneider'

    # Copyright
    Copyright = '2026 Niklas Schneider'

    # Description of the module functions
    Description = 'PowerShell Network Administration Tool'

    # PSData of the module
    PrivateData = @{
        PSData = @{
            Tags = @('NetworkAdministration', 'ActiveDirectory', 'RemoteManagement', 'Windows', 'Administration', 'Admin')
            LicenseUri = 'https://github.com/NiklasSkulll/PSNetworkAdministrator/blob/main/LICENSE'
            ProjectUri = 'https://github.com/NiklasSkulll/PSNetworkAdministrator'
            # IconUri = ''
            ReleaseNotes = 'Initial release - Active Directory computer management and availability checking'
            # Prerelease = 'alpha'
            # RequireLicenseAcceptance = $false
            # ExternalModuleDependencies = @()
        }
    }

    # functions to export from this module
    FunctionsToExport = @(
        'Add-DataToSQLite',
        'Add-Domain',
        'Add-DomainCredentials',
        'Get-ComputerAvailability',
        'Get-ComputerHardwareInfo',
        'Get-DomainComputers',
        'Get-DomainCredentials',
        'Initialize-Domain',
        'Remove-DataFromSQLite',
        'Remove-DomainCredentials'
    )
}