# ------------------------------
# module "PSNetworkAdministrator"
# generated by: Niklas Schneider
# generated on: 02.02.2026
# ------------------------------

# dot-source all private functions
Get-ChildItem -Path "$PSScriptRoot\Private\*.ps1" | ForEach-Object {
    . $_.FullName
}

# dot-source all public functions
Get-ChildItem -Path "$PSScriptRoot\Public\*.ps1" -ErrorAction SilentlyContinue | ForEach-Object {
    . $_.FullName
}

# check and install CredentialManager if needed
if (-not (Get-Module -ListAvailable -Name CredentialManager)) {
    Install-Module -Name CredentialManager -Force -Scope CurrentUser
}

# check ActiveDirectory
if (-not (Get-Module -ListAvailable -Name ActiveDirectory)) {
    throw "ActiveDirectory module not found. Install RSAT tools: Add-WindowsCapability -Online -Name Rsat.ActiveDirectory.DS-LDS.Tools~~~~0.0.1.0"
}

# import Modules
Import-Module CredentialManager -ErrorAction Stop
Import-Module ActiveDirectory -ErrorAction Stop

# load config and initialize the path and max logging size for logs
try {
    $script:ModuleConfig = Initialize-Configuration
    $script:LoggingPath = $script:ModuleConfig.Logging.LoggingPath
    $script:MaxLogSizeMB = $script:ModuleConfig.Logging.MaxLoggingSizeMB
}
catch {
    $script:LoggingPath = "logs/PSNetAdmin.log"
    Write-Warning "Failed to load config, using default log path: $($script:LoggingPath)"
}