name: 📚 Documentation Improvement
description: Report issues with documentation or suggest documentation improvements.
title: "[DOCS] "
labels: ['documentation', 'priority: low', 'priority: medium', 'priority: high']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Clear documentation is crucial for user adoption and success.
        Please provide as much detail as possible about what needs to be improved.

  - type: input
    id: summary
    attributes:
      label: 📋 **Documentation Issue Summary**
      description: A brief description of the documentation problem or improvement needed.
      placeholder: "e.g. Get-NetworkDiagnostics examples are outdated and don't show all parameters"
    validations:
      required: true

  - type: dropdown
    id: doc_type
    attributes:
      label: 📖 **Documentation Type**
      options:
        - README.md
        - Function Help (Get-Help)
        - Code Comments
        - Examples/Tutorials
        - Installation Guide
        - Troubleshooting Guide
        - API Reference
        - Other
      description: What type of documentation needs attention?
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: 📍 **Location & Context**
      description: Where is the documentation issue? Provide file paths, function names, or section references.
      placeholder: |
        File: README.md, section "Quick Start"
        Function: Get-NetworkDiagnostics
        Line/Section: Lines 45-60
        URL: (if applicable)
    validations:
      required: true

  - type: dropdown
    id: issue_type
    attributes:
      label: 🔍 **Issue Type**
      options:
        - Missing documentation
        - Outdated/incorrect information
        - Unclear/confusing explanation
        - Missing examples
        - Broken links/references
        - Formatting issues
        - Typos/grammar
        - Missing parameter documentation
        - Other
      description: What kind of documentation issue is this?
    validations:
      required: true

  - type: textarea
    id: current_content
    attributes:
      label: 📄 **Current Content (if applicable)**
      description: Copy the current documentation text that needs improvement.
      placeholder: |
        ```markdown
        ## Quick Start
        Run the following command to get started:
        Get-NetworkInfo
        ```

  - type: textarea
    id: expected_content
    attributes:
      label: ✨ **Suggested Improvement**
      description: How should the documentation be improved? Provide specific suggestions or new content.
      placeholder: |
        ```markdown
        ## Quick Start
        1. Import the module: `Import-Module NetworkAdmin`
        2. Get basic network information: `Get-NetworkDiagnostics -ComputerName "localhost"`
        3. For remote computers: `Get-NetworkDiagnostics -ComputerName "RemotePC" -Credential (Get-Credential)`
        ```
    validations:
      required: true

  - type: textarea
    id: user_impact
    attributes:
      label: 👥 **User Impact**
      description: How does this documentation issue affect users? Who would benefit from the improvement?
      placeholder: |
        - New users can't get started quickly
        - Advanced users missing parameter information
        - Confusion leads to support requests
        - Feature discoverability is poor

  - type: textarea
    id: examples_needed
    attributes:
      label: 💡 **Examples Needed**
      description: What specific examples or scenarios should be documented?
      placeholder: |
        Examples needed for:
        - Basic usage with local computer
        - Remote computer scenarios
        - Error handling
        - Integration with other functions
        - Real-world use cases

  - type: checkboxes
    id: documentation_improvements
    attributes:
      label: 📝 **Additional Improvements**
      description: Select any additional improvements that would be helpful
      options:
        - label: Add more code examples
        - label: Include troubleshooting section
        - label: Add parameter validation examples
        - label: Include performance considerations
        - label: Add cross-references to related functions
        - label: Include security considerations
        - label: Add prerequisite information
  - type: dropdown
    id: priority
    attributes:
      label: 🚩 **Priority**
      options:
        - priority: low
        - priority: medium
        - priority: high
      default: 0
      description: How important is this documentation improvement?

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 **Contribution Willingness**
      description: Are you willing to help improve this documentation?
      options:
        - label: I can write the improved documentation
        - label: I can review documentation changes
        - label: I can provide additional examples
        - label: I can test documentation accuracy

  - type: textarea
    id: additional_context
    attributes:
      label: 📚 **Additional Context**
      description: Any additional information, links, or context that would be helpful.
      placeholder: |
        - Related functions that should be cross-referenced
        - External documentation that could be referenced
        - User feedback or questions that prompted this request
        - Screenshots showing the current state

  - type: markdown
    attributes:
      value: |
        ---  
        Once you've filled out all sections, click **Submit new issue**.  
        Thank you for helping us improve our documentation! 📚
